const classes = [
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "14/09/2026",
        start: "8:30",
        end: "10:00",
        type: "Plenary1",
        title: "Space Occupying Lesions",
        teachers: "Natasha Kumar, Sophia Champion, Jacob Fairhall",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "14/09/2026",
        start: "10:00",
        end: "11:00",
        type: "L1",
        title: "Cranial cavity and Introduction to the brain",
        teachers: "Kosta Kotsidis",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "14/09/2026",
        start: "11:00",
        end: "12:00",
        type: "L2",
        title: "Molecular biology of cell growth and neoplasia",
        teachers: "Frances Byrne",
        groups: "",
        location: "recording"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "14/09/2026",
        start: "12:00",
        end: "14:00",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "D8,9",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "14/09/2026",
        start: "13:00",
        end: "15:00",
        type: "SG1",
        title: "This is your Brain",
        teachers: "Tom Duncan",
        groups: "A",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "14/09/2026",
        start: "14:30",
        end: "16:30",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "D6,7",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "14/09/2026",
        start: "15:00",
        end: "17:00",
        type: "SG1",
        title: "This is your Brain",
        teachers: "Tom Duncan",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/09/2026",
        start: "9:00",
        end: "10:00",
        type: "L3",
        title: "Forebrain: Anatomical Organisation & Cortical Function",
        teachers: "Kosta Kotsidis",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/09/2026",
        start: "10:00",
        end: "11:00",
        type: "L4",
        title: "Basic Cellular Physiology of Brain Function",
        teachers: "Catherine Guo",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/09/2026",
        start: "11:00",
        end: "12:00",
        type: "L5",
        title: "Neuro-imaging",
        teachers: "Michael Green",
        groups: "",
        location: "Ritchie Th"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/09/2026",
        start: "12:00",
        end: "14:00",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "B8,9",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/09/2026",
        start: "13:00",
        end: "15:00",
        type: "SG1",
        title: "This is your Brain",
        teachers: "Tom Duncan",
        groups: "D",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/09/2026",
        start: "14:30",
        end: "16:30",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "B6,7",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/09/2026",
        start: "15:00",
        end: "17:00",
        type: "SG1",
        title: "This is your Brain",
        teachers: "Tom Duncan",
        groups: "C",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "16/09/2026",
        start: "9:00",
        end: "10:00",
        type: "L6",
        title: "Biology of Normal Ageing",
        teachers: "Linda Ferrington",
        groups: "",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "16/09/2026",
        start: "10:00",
        end: "11:00",
        type: "L7",
        title: "Neuron Ultrastructure",
        teachers: "Kosta Kotsidis",
        groups: "",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "16/09/2026",
        start: "11:00",
        end: "12:00",
        type: "L8",
        title: "Intracranial Space-Occupying Lesions - Pathology",
        teachers: "Sophia Champion",
        groups: "",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "16/09/2026",
        start: "12:00",
        end: "14:00",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "C8,9",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "16/09/2026",
        start: "13:00",
        end: "15:00",
        type: "SG2",
        title: "The Brain and Self",
        teachers: "Natasha Kumar",
        groups: "A",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "16/09/2026",
        start: "14:30",
        end: "16:30",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "C6,7",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "16/09/2026",
        start: "15:00",
        end: "17:00",
        type: "SG2",
        title: "The Brain and Self",
        teachers: "Natasha Kumar",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "17/09/2026",
        start: "9:00",
        end: "10:00",
        type: "L9",
        title: "Physiological Mechanisms of Neuronal Potentials",
        teachers: "Catherine Guo",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "17/09/2026",
        start: "10:00",
        end: "11:00",
        type: "L10",
        title: "Pharmacological manipulation of neurotransmitters",
        teachers: "Natasha Kumar",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "17/09/2026",
        start: "11:00",
        end: "12:00",
        type: "L11",
        title: "Synaptic Transmission – Mechanisms and Plasticity",
        teachers: "Catherine Guo",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "17/09/2026",
        start: "12:00",
        end: "14:00",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "A8,9",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "17/09/2026",
        start: "13:00",
        end: "15:00",
        type: "SG2",
        title: "The Brain and Self",
        teachers: "Natasha Kumar",
        groups: "D",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "17/09/2026",
        start: "13:00",
        end: "15:00",
        type: "P1",
        title: "Cranial cavity and Introduction to Brain",
        teachers: "Kosta Kotsidis",
        groups: "C1-8",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "17/09/2026",
        start: "14:30",
        end: "16:30",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "A6,7",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "17/09/2026",
        start: "15:00",
        end: "17:00",
        type: "SG2",
        title: "The Brain and Self",
        teachers: "Natasha Kumar",
        groups: "C",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "17/09/2026",
        start: "15:00",
        end: "17:00",
        type: "P1",
        title: "Cranial cavity and Introduction to Brain",
        teachers: "Kosta Kotsidis",
        groups: "B1-8",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "18/09/2026",
        start: "9:00",
        end: "11:00",
        type: "P1",
        title: "Cranial cavity and Introduction to Brain",
        teachers: "Kosta Kotsidis",
        groups: "D5,10,A5,10,C9,10,B9,10",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "18/09/2026",
        start: "9:00",
        end: "11:00",
        type: "P2",
        title: "Membrane potentials",
        teachers: "Catherine Guo",
        groups: "A6-9,A1-4",
        location: "WW115"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "18/09/2026",
        start: "11:00",
        end: "13:00",
        type: "P1",
        title: "Cranial cavity and Introduction to Brain",
        teachers: "Kosta Kotsidis",
        groups: "D1-4,D6-9",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "18/09/2026",
        start: "12:00",
        end: "14:00",
        type: "P2",
        title: "Membrane potentials",
        teachers: "Catherine Guo",
        groups: "B9-10,C9-10,B1,2,C1,2",
        location: "WW115"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "18/09/2026",
        start: "13:00",
        end: "15:00",
        type: "P1",
        title: "Cranial cavity and Introduction to Brain",
        teachers: "Kosta Kotsidis",
        groups: "A1-4,A6-9",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "18/09/2026",
        start: "15:00",
        end: "17:00",
        type: "P2",
        title: "Membrane potentials",
        teachers: "Catherine Guo",
        groups: "D5,10,A5,10,D6-9",
        location: "WW115"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "18/09/2026",
        start: "12:00",
        end: "14:00",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "A10,D10",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "18/09/2026",
        start: "14:30",
        end: "16:30",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "B10,C10",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/09/2026",
        start: "9:00",
        end: "10:00",
        type: "L12",
        title: "Forebrain: Internal Capsule & subcortical tracts",
        teachers: "Reza Shirazi",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/09/2026",
        start: "10:00",
        end: "11:00",
        type: "L13",
        title: "Central Somatosensory System",
        teachers: "Ismail Devecioglu",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/09/2026",
        start: "13:00",
        end: "15:00",
        type: "SG3",
        title: "Intracrainal Space Occupying Lesions",
        teachers: "Andrew Dubovyi, Martin Weber",
        groups: "A",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/09/2026",
        start: "15:00",
        end: "17:00",
        type: "SG3",
        title: "Intracrainal Space Occupying Lesions",
        teachers: "Andrew Dubovyi, Martin Weber",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/09/2026",
        start: "13:00",
        end: "14:00",
        type: "T1",
        title: "Pathology SOL",
        teachers: "Sophia Champion",
        groups: "C",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/09/2026",
        start: "14:00",
        end: "15:00",
        type: "T1",
        title: "Pathology SOL",
        teachers: "Sophia Champion",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/09/2026",
        start: "15:00",
        end: "16:00",
        type: "T1",
        title: "Pathology SOL",
        teachers: "Sophia Champion",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/09/2026",
        start: "11:00",
        end: "13:00",
        type: "P2",
        title: "Membrane potentials",
        teachers: "Catherine Guo",
        groups: "B3-7,C3.1",
        location: "WW120"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/09/2026",
        start: "13:30",
        end: "15:30",
        type: "P2",
        title: "Membrane potentials",
        teachers: "Catherine Guo",
        groups: "B8,D1-4",
        location: "WW120"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/09/2026",
        start: "16:00",
        end: "18:00",
        type: "P2",
        title: "Membrane potentials",
        teachers: "Catherine Guo",
        groups: "C3.2-8",
        location: "WW120"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/09/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos1",
        title: "Examining the Neurological System: Upper and lower limbs",
        teachers: "Kalli Spencer",
        groups: "D6-10",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/09/2026",
        start: "12:00",
        end: "14:00",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "D3,4",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/09/2026",
        start: "14:30",
        end: "16:30",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "D1,2",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/09/2026",
        start: "9:00",
        end: "10:00",
        type: "L14",
        title: "Nutrition for the Older Adult",
        teachers: "Ryan Anthony",
        groups: "",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/09/2026",
        start: "10:00",
        end: "11:00",
        type: "L15",
        title: "Meningitis",
        teachers: "Fang Liu",
        groups: "",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/09/2026",
        start: "13:00",
        end: "15:00",
        type: "SG3",
        title: "Intracrainal Space Occupying Lesions",
        teachers: "Andrew Dubovyi, Martin Weber",
        groups: "D",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/09/2026",
        start: "15:00",
        end: "17:00",
        type: "SG3",
        title: "Intracrainal Space Occupying Lesions",
        teachers: "Andrew Dubovyi, Martin Weber",
        groups: "C",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/09/2026",
        start: "11:00",
        end: "13:00",
        type: "P3",
        title: "Behavioural Screening of CNS Drugs (Pharmacology; Neurophysiology)",
        teachers: "Natasha Kumar",
        groups: "C",
        location: "WWG06"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/09/2026",
        start: "15:00",
        end: "17:00",
        type: "P3",
        title: "Behavioural Screening of CNS Drugs (Pharmacology; Neurophysiology)",
        teachers: "Natasha Kumar",
        groups: "D",
        location: "WWG06"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/09/2026",
        start: "12:00",
        end: "13:00",
        type: "T1",
        title: "Pathology SOL",
        teachers: "Sophia Champion",
        groups: "D",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/09/2026",
        start: "14:00",
        end: "15:00",
        type: "T2",
        title: "Harry has hydrocephalus",
        teachers: "Kosta Kotsidis",
        groups: "A,C",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/09/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos1",
        title: "Examining the Neurological System: Upper and lower limbs",
        teachers: "Kalli Spencer",
        groups: "B6-10",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/09/2026",
        start: "12:00",
        end: "14:00",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "B3,4",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/09/2026",
        start: "14:30",
        end: "16:30",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "B1,2",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "23/09/2026",
        start: "9:00",
        end: "10:00",
        type: "L16",
        title: "Ethics: consent, how can it be informed",
        teachers: "Sarah Baldwin",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "23/09/2026",
        start: "10:00",
        end: "11:00",
        type: "L17",
        title: "Motor System 1 - Reflex",
        teachers: "Frederic Von Wegner",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "23/09/2026",
        start: "13:00",
        end: "15:00",
        type: "SG4",
        title: "Caring for older adults",
        teachers: "Louise Baird, Katya Numbers, Natasha Kumar",
        groups: "A",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "23/09/2026",
        start: "15:00",
        end: "17:00",
        type: "SG4",
        title: "Caring for older adults",
        teachers: "Louise Baird, Katya Numbers, Natasha Kumar",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "23/09/2026",
        start: "11:00",
        end: "13:00",
        type: "P3",
        title: "Behavioural Screening of CNS Drugs (Pharmacology; Neurophysiology)",
        teachers: "Natasha Kumar",
        groups: "A",
        location: "WWG06-07"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "23/09/2026",
        start: "13:00",
        end: "15:00",
        type: "P3",
        title: "Behavioural Screening of CNS Drugs (Pharmacology; Neurophysiology)",
        teachers: "Natasha Kumar",
        groups: "B",
        location: "WWG06-07"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "23/09/2026",
        start: "11:00",
        end: "12:00",
        type: "T2",
        title: "Harry has hydrocephalus",
        teachers: "Kosta Kotsidis",
        groups: "B,D",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "23/09/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos1",
        title: "Examining the Neurological System: Upper and lower limbs",
        teachers: "Kalli Spencer",
        groups: "C6-10",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "23/09/2026",
        start: "12:00",
        end: "14:00",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "C3,4",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "23/09/2026",
        start: "14:30",
        end: "16:30",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "C1,2",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "24/09/2026",
        start: "9:00",
        end: "10:00",
        type: "L18",
        title: "Information Session on the Prac Exam",
        teachers: "Marty Le Nedelec",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "24/09/2026",
        start: "10:00",
        end: "11:00",
        type: "L19",
        title: "Motor System 2 - Spinal pathways and motor cortices",
        teachers: "Frederic Von Wegner",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "24/09/2026",
        start: "11:00",
        end: "12:00",
        type: "L20",
        title: "Brainstem",
        teachers: "Kosta Kotsidis",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "24/09/2026",
        start: "13:00",
        end: "15:00",
        type: "SG4",
        title: "Caring for older adults",
        teachers: "Louise Baird, Katya Numbers, Natasha Kumar",
        groups: "D",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "24/09/2026",
        start: "15:00",
        end: "17:00",
        type: "SG4",
        title: "Caring for older adults",
        teachers: "Louise Baird, Katya Numbers, Natasha Kumar",
        groups: "C",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "24/09/2026",
        start: "13:00",
        end: "15:00",
        type: "P4",
        title: "Forebrain: Functional Localisation & Subcortical Tracts",
        teachers: "Kosta Kotsidis",
        groups: "C1-8",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "24/09/2026",
        start: "15:00",
        end: "17:00",
        type: "P4",
        title: "Forebrain: Functional Localisation & Subcortical Tracts",
        teachers: "Kosta Kotsidis",
        groups: "B1-8",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "24/09/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos1",
        title: "Examining the Neurological System: Upper and lower limbs",
        teachers: "Kalli Spencer",
        groups: "A6-10",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "24/09/2026",
        start: "12:00",
        end: "14:00",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "A3,4",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "24/09/2026",
        start: "14:30",
        end: "16:30",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "A1,2",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "25/09/2026",
        start: "9:00",
        end: "11:00",
        type: "P4",
        title: "Forebrain: Functional Localisation & Subcortical Tracts",
        teachers: "Kosta Kotsidis",
        groups: "D5,10,A5,10,C9,10,B9,10",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "25/09/2026",
        start: "11:00",
        end: "13:00",
        type: "P4",
        title: "Forebrain: Functional Localisation & Subcortical Tracts",
        teachers: "Kosta Kotsidis",
        groups: "D1-4,D6-9",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "25/09/2026",
        start: "13:00",
        end: "15:00",
        type: "P4",
        title: "Forebrain: Functional Localisation & Subcortical Tracts",
        teachers: "Kosta Kotsidis",
        groups: "A1-4,A6-9",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "25/09/2026",
        start: "9:00",
        end: "11:00",
        type: "P5",
        title: "Analysis of cell ageing",
        teachers: "Dhanushi Abeygunawardena",
        groups: "D1,2,9,A3",
        location: "WW122"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "25/09/2026",
        start: "12:00",
        end: "14:00",
        type: "P5",
        title: "Analysis of cell ageing",
        teachers: "Dhanushi Abeygunawardena",
        groups: "B1,2,10,D10",
        location: "WW122"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "25/09/2026",
        start: "15:00",
        end: "17:00",
        type: "P5",
        title: "Analysis of cell ageing",
        teachers: "Dhanushi Abeygunawardena",
        groups: "D6,7,8,5",
        location: "WW122"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "25/09/2026",
        start: "9:00",
        end: "11:00",
        type: "P5",
        title: "Analysis of cell ageing",
        teachers: "Dhanushi Abeygunawardena",
        groups: "A4,B5,D3,4",
        location: "WW123"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "25/09/2026",
        start: "12:00",
        end: "14:00",
        type: "P5",
        title: "Analysis of cell ageing",
        teachers: "Dhanushi Abeygunawardena",
        groups: "B3,4,C3,4",
        location: "WW123"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "25/09/2026",
        start: "15:00",
        end: "17:00",
        type: "P5",
        title: "Analysis of cell ageing",
        teachers: "Dhanushi Abeygunawardena",
        groups: "B6-9",
        location: "WW123"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "25/09/2026",
        start: "12:00",
        end: "14:00",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "A5,D5",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "25/09/2026",
        start: "14:30",
        end: "16:30",
        type: "CS1",
        title: "Neurological history and examination",
        teachers: "Kalli Spencer",
        groups: "B5,C5",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/09/2026",
        start: "9:00",
        end: "10:00",
        type: "Plenary2",
        title: "Stroke Plenary",
        teachers: "Gary Velan, Ken Butcher",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/09/2026",
        start: "10:00",
        end: "11:00",
        type: "L21",
        title: "Cerebral Blood Supply",
        teachers: "Kosta Kotsidis",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/09/2026",
        start: "11:00",
        end: "12:00",
        type: "T3",
        title: "Consent and Law",
        teachers: "Sarah Baldwin",
        groups: "A",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/09/2026",
        start: "12:00",
        end: "13:00",
        type: "T3",
        title: "Consent and Law",
        teachers: "Sarah Baldwin",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/09/2026",
        start: "13:00",
        end: "15:00",
        type: "SG5",
        title: "Stroke: No Postcode Untouched",
        teachers: "Fred von Wegner, Linda Ferrington",
        groups: "A",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/09/2026",
        start: "15:00",
        end: "17:00",
        type: "SG5",
        title: "Stroke: No Postcode Untouched",
        teachers: "Fred von Wegner, Linda Ferrington",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/09/2026",
        start: "12:00",
        end: "14:00",
        type: "P5",
        title: "Analysis of cell ageing",
        teachers: "Dhanushi Abeygunawardena",
        groups: "C1,2,9,10",
        location: "WW122"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/09/2026",
        start: "15:00",
        end: "17:00",
        type: "P5",
        title: "Analysis of cell ageing",
        teachers: "Dhanushi Abeygunawardena",
        groups: "A1,2,9,10",
        location: "WW122"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/09/2026",
        start: "12:00",
        end: "14:00",
        type: "P5",
        title: "Analysis of cell ageing",
        teachers: "Dhanushi Abeygunawardena",
        groups: "C5-8",
        location: "WW123"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/09/2026",
        start: "15:00",
        end: "17:00",
        type: "P5",
        title: "Analysis of cell ageing",
        teachers: "Dhanushi Abeygunawardena",
        groups: "A5-8",
        location: "WW123"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/09/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos1",
        title: "Examining the Neurological System: Upper and lower limbs",
        teachers: "Kalli Spencer",
        groups: "D1-5",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/09/2026",
        start: "12:00",
        end: "14:00",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "D8,9",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/09/2026",
        start: "14:30",
        end: "16:30",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "D6,7",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "29/09/2026",
        start: "9:00",
        end: "10:00",
        type: "L22",
        title: "Cerebrovascular Disease 1: Infarction",
        teachers: "Gary Velan",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "29/09/2026",
        start: "10:00",
        end: "11:00",
        type: "L23",
        title: "Cerebrovascular Disease 2: Haemorrhage",
        teachers: "Gary Velan",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "29/09/2026",
        start: "11:00",
        end: "12:00",
        type: "T3",
        title: "Consent and Law",
        teachers: "Sarah Baldwin",
        groups: "D",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "29/09/2026",
        start: "12:00",
        end: "13:00",
        type: "T3",
        title: "Consent and Law",
        teachers: "Sarah Baldwin",
        groups: "C",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "29/09/2026",
        start: "13:00",
        end: "15:00",
        type: "SG5",
        title: "Stroke: No Postcode Untouched",
        teachers: "Fred von Wegner, Linda Ferrington",
        groups: "D",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "29/09/2026",
        start: "15:00",
        end: "17:00",
        type: "SG5",
        title: "Stroke: No Postcode Untouched",
        teachers: "Fred von Wegner, Linda Ferrington",
        groups: "C",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "29/09/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos1",
        title: "Examining the Neurological System: Upper and lower limbs",
        teachers: "Kalli Spencer",
        groups: "B1-5",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "29/09/2026",
        start: "12:00",
        end: "14:00",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "B8,9",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "29/09/2026",
        start: "14:30",
        end: "16:30",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "B6,7",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "30/09/2026",
        start: "9:00",
        end: "10:00",
        type: "L24",
        title: "Vision 1: Eye and optics",
        teachers: "Catherine Guo",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "30/09/2026",
        start: "10:00",
        end: "11:00",
        type: "L25",
        title: "Clinical Skils in AEB",
        teachers: "Kalli Spencer, Sue Britton",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "30/09/2026",
        start: "13:00",
        end: "15:00",
        type: "SG6",
        title: "Stroke Cases",
        teachers: "Fred von Wegner, Amir Ariff",
        groups: "A",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "30/09/2026",
        start: "15:00",
        end: "17:00",
        type: "SG6",
        title: "Stroke Cases",
        teachers: "Fred von Wegner, Amir Ariff",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "30/09/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos1",
        title: "Examining the Neurological System: Upper and lower limbs",
        teachers: "Kalli Spencer",
        groups: "C1-5",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "30/09/2026",
        start: "12:00",
        end: "14:00",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "C8,9",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "30/09/2026",
        start: "14:30",
        end: "16:30",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "C6,7",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "01/10/2026",
        start: "9:00",
        end: "10:00",
        type: "L26",
        title: "Vision 2: Central pathways/cortex",
        teachers: "Catherine Guo",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "01/10/2026",
        start: "10:00",
        end: "11:00",
        type: "L27",
        title: "Pharmacological approaches to stroke",
        teachers: "Nicole Jones",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "01/10/2026",
        start: "11:00",
        end: "12:00",
        type: "L28",
        title: "Cranial Nerves 1",
        teachers: "Tom Duncan",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "01/10/2026",
        start: "13:00",
        end: "15:00",
        type: "SG6",
        title: "Stroke Cases",
        teachers: "Fred von Wegner, Amir Ariff",
        groups: "D",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "01/10/2026",
        start: "15:00",
        end: "17:00",
        type: "SG6",
        title: "Stroke Cases",
        teachers: "Fred von Wegner, Amir Ariff",
        groups: "C",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "01/10/2026",
        start: "13:00",
        end: "15:00",
        type: "P6",
        title: "Brain and Blood Supply",
        teachers: "Kosta Kotsidis",
        groups: "C1-8",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "01/10/2026",
        start: "15:00",
        end: "17:00",
        type: "P6",
        title: "Brain and Blood Supply",
        teachers: "Kosta Kotsidis",
        groups: "B1-8",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "01/10/2026",
        start: "12:00",
        end: "14:00",
        type: "P7",
        title: "Myotatic reflexes and the H-reflex",
        teachers: "Fred van Wegner",
        groups: "B5-10,C9-10",
        location: "WW115"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "01/10/2026",
        start: "15:00",
        end: "17:00",
        type: "P7",
        title: "Myotatic reflexes and the H-reflex",
        teachers: "Fred van Wegner",
        groups: "D3-10",
        location: "WW115"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "01/10/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos1",
        title: "Examining the Neurological System: Upper and lower limbs",
        teachers: "Kalli Spencer",
        groups: "A1-5",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "01/10/2026",
        start: "12:00",
        end: "14:00",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "A8,9",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "01/10/2026",
        start: "14:30",
        end: "16:30",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "A6,7",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "02/10/2026",
        start: "9:00",
        end: "11:00",
        type: "P6",
        title: "Brain and Blood Supply",
        teachers: "Kosta Kotsidis",
        groups: "D5,10,A5,10,C9,10,B9,10",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "02/10/2026",
        start: "11:00",
        end: "13:00",
        type: "P6",
        title: "Brain and Blood Supply",
        teachers: "Kosta Kotsidis",
        groups: "D1-4,D6-9",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "02/10/2026",
        start: "13:00",
        end: "15:00",
        type: "P6",
        title: "Brain and Blood Supply",
        teachers: "Kosta Kotsidis",
        groups: "A1-4,A6-9",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "02/10/2026",
        start: "9:00",
        end: "11:00",
        type: "P7",
        title: "Myotatic reflexes and the H-reflex",
        teachers: "Fred van Wegner",
        groups: "C1-4,A8-9,D1,2",
        location: "WW115"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "02/10/2026",
        start: "12:00",
        end: "14:00",
        type: "P7",
        title: "Myotatic reflexes and the H-reflex",
        teachers: "Fred van Wegner",
        groups: "C5-8,B1-4",
        location: "WW115"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "02/10/2026",
        start: "15:00",
        end: "17:00",
        type: "P7",
        title: "Myotatic reflexes and the H-reflex",
        teachers: "Fred van Wegner",
        groups: "A1-7,10",
        location: "WW115"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "02/10/2026",
        start: "9:00",
        end: "11:00",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "D3,D4",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "02/10/2026",
        start: "12:00",
        end: "14:00",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "A10,D10",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "02/10/2026",
        start: "14:30",
        end: "16:30",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "B10,C10",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "06/10/2026",
        start: "9:00",
        end: "10:00",
        type: "L29",
        title: "Cranial Nerves 2",
        teachers: "Tom Duncan",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "06/10/2026",
        start: "10:00",
        end: "11:00",
        type: "L30",
        title: "The Older Aboriginal Person - Introduction",
        teachers: "Miriam Cavanagh",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "07/10/2026",
        start: "15:00",
        end: "17:00",
        type: "P8",
        title: "CNS: Normal and abnormal (Histology, Pathology)",
        teachers: "Sophia Champion, Reza Shirazi",
        groups: "D",
        location: "WWG06-07"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "06/10/2026",
        start: "15:00",
        end: "17:00",
        type: "P8",
        title: "CNS: Normal and abnormal (Histology, Pathology)",
        teachers: "Sophia Champion, Reza Shirazi",
        groups: "C",
        location: "WWG06-07"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "06/10/2026",
        start: "11:00",
        end: "12:00",
        type: "T4",
        title: "Pathology stroke",
        teachers: "Martin Weber",
        groups: "D",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "06/10/2026",
        start: "12:00",
        end: "13:00",
        type: "T4",
        title: "Pathology stroke",
        teachers: "Martin Weber",
        groups: "C",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "06/10/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos2",
        title: "Examining the neurological system: cranial nerves",
        teachers: "Kalli Spencer",
        groups: "B6-10",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "06/10/2026",
        start: "12:00",
        end: "14:00",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "B3,4",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "06/10/2026",
        start: "14:30",
        end: "16:30",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "B1,2",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "07/10/2026",
        start: "9:00",
        end: "10:00",
        type: "L31",
        title: "Stroke Outcomes / Rehabilitation",
        teachers: "Steven Faux",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "07/10/2026",
        start: "10:00",
        end: "11:00",
        type: "L32",
        title: "Cranial Nerves 3",
        teachers: "Tom Duncan",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "07/10/2026",
        start: "13:00",
        end: "15:00",
        type: "SG7",
        title: "Older Indigenous People",
        teachers: "Miriam, Melody, Frederic von Wegner",
        groups: "A",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "07/10/2026",
        start: "15:00",
        end: "17:00",
        type: "SG7",
        title: "Older Indigenous People",
        teachers: "Miriam, Melody, Frederic von Wegner",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "07/10/2026",
        start: "11:00",
        end: "12:00",
        type: "T4",
        title: "Pathology stroke",
        teachers: "Martin Weber",
        groups: "A",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "07/10/2026",
        start: "12:00",
        end: "13:00",
        type: "T4",
        title: "Pathology stroke",
        teachers: "Martin Weber",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "07/10/2026",
        start: "13:00",
        end: "15:00",
        type: "P8",
        title: "CNS: Normal and abnormal (Histology, Pathology)",
        teachers: "Sophia Champion, Reza Shirazi",
        groups: "B",
        location: "WWG06-07"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "07/10/2026",
        start: "15:00",
        end: "17:00",
        type: "P8",
        title: "CNS: Normal and abnormal (Histology, Pathology)",
        teachers: "Sophia Champion, Reza Shirazi",
        groups: "A",
        location: "WWG06-07"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "06/10/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos2",
        title: "Examining the neurological system: cranial nerves",
        teachers: "Kalli Spencer",
        groups: "D6-10",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "07/10/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos2",
        title: "Examining the neurological system: cranial nerves",
        teachers: "Kalli Spencer",
        groups: "C6-10",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "07/10/2026",
        start: "12:00",
        end: "14:00",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "C3,4",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "07/10/2026",
        start: "14:30",
        end: "16:30",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "C1,2",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "08/10/2026",
        start: "9:00",
        end: "10:00",
        type: "L33",
        title: "Higher Cortical Function 1 - Memory",
        teachers: "John Power",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "08/10/2026",
        start: "10:00",
        end: "11:00",
        type: "L34",
        title: "QMP - Weighing the Evidence",
        teachers: "Amir Ariff",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "08/10/2026",
        start: "11:00",
        end: "12:00",
        type: "T5",
        title: "Blood Supply",
        teachers: "Kosta Kotsidis",
        groups: "",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "08/10/2026",
        start: "13:00",
        end: "15:00",
        type: "SG7",
        title: "Older Indigenous People",
        teachers: "Miriam, Melody, Frederic von Wegner",
        groups: "D",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "08/10/2026",
        start: "15:00",
        end: "17:00",
        type: "SG7",
        title: "Older Indigenous People",
        teachers: "Miriam, Melody, Frederic von Wegner",
        groups: "C",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "08/10/2026",
        start: "13:00",
        end: "15:00",
        type: "P9",
        title: "Cranial nerves",
        teachers: "Tom Duncan",
        groups: "C1-8",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "08/10/2026",
        start: "15:00",
        end: "17:00",
        type: "P9",
        title: "Cranial nerves",
        teachers: "Tom Duncan",
        groups: "B1-8",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "08/10/2026",
        start: "12:00",
        end: "14:00",
        type: "P10",
        title: "Visual Physiology",
        teachers: "Catherine Guo",
        groups: "B5-10,C9-10",
        location: "WW115"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "08/10/2026",
        start: "15:00",
        end: "17:00",
        type: "P10",
        title: "Visual Physiology",
        teachers: "Catherine Guo",
        groups: "D3-10",
        location: "WW115"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "08/10/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos2",
        title: "Examining the neurological system: cranial nerves",
        teachers: "Kalli Spencer",
        groups: "A6-10",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "08/10/2026",
        start: "12:00",
        end: "14:00",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "A3,4",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "08/10/2026",
        start: "14:30",
        end: "16:30",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "A1,2",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "09/10/2026",
        start: "9:00",
        end: "11:00",
        type: "P9",
        title: "Cranial nerves",
        teachers: "Tom Duncan",
        groups: "D5,10,A5,10,C9,10,B9,10",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "09/10/2026",
        start: "11:00",
        end: "13:00",
        type: "P9",
        title: "Cranial nerves",
        teachers: "Tom Duncan",
        groups: "D1-4,D6-9",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "09/10/2026",
        start: "13:00",
        end: "15:00",
        type: "P9",
        title: "Cranial nerves",
        teachers: "Tom Duncan",
        groups: "A1-4,A6-9",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "09/10/2026",
        start: "9:00",
        end: "11:00",
        type: "P10",
        title: "Visual Physiology",
        teachers: "Catherine Guo",
        groups: "C1-4,A8-9,D1,2",
        location: "WW115"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "09/10/2026",
        start: "12:00",
        end: "14:00",
        type: "P10",
        title: "Visual Physiology",
        teachers: "Catherine Guo",
        groups: "C5-8,B1-4",
        location: "WW115"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "09/10/2026",
        start: "15:00",
        end: "17:00",
        type: "P10",
        title: "Visual Physiology",
        teachers: "Catherine Guo",
        groups: "A1-7,10",
        location: "WW115"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "09/10/2026",
        start: "9:00",
        end: "11:00",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "D1,2",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "09/10/2026",
        start: "12:00",
        end: "14:00",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "A5,D5",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "09/10/2026",
        start: "14:30",
        end: "16:30",
        type: "CS2",
        title: "Common problems in the elderly and the CNS examination",
        teachers: "Kalli Spencer",
        groups: "B5,C5",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "12/10/2026",
        start: "9:00",
        end: "10:00",
        type: "L35",
        title: "Functional Anatomy of the Basal Ganglia",
        teachers: "Tom Duncan",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "12/10/2026",
        start: "10:00",
        end: "11:00",
        type: "L36",
        title: "Limbic System and Emotions",
        teachers: "Tom Duncan",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "12/10/2026",
        start: "13:00",
        end: "15:00",
        type: "SG8",
        title: "Cranial Nerve Lesion",
        teachers: "Tom Duncan",
        groups: "A",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "12/10/2026",
        start: "15:00",
        end: "17:00",
        type: "SG8",
        title: "Cranial Nerve Lesion",
        teachers: "Tom Duncan",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "12/10/2026",
        start: "11:00",
        end: "13:00",
        type: "P11",
        title: "QMP Weighing the Evidence",
        teachers: "Amir Ariff",
        groups: "B",
        location: "WWG06-07"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "12/10/2026",
        start: "15:00",
        end: "16:00",
        type: "T6",
        title: "Cranial Nerve Lesions",
        teachers: "Tom Duncan",
        groups: "A,C",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "12/10/2026",
        start: "12:00",
        end: "14:00",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "D8,9",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "12/10/2026",
        start: "14:30",
        end: "16:30",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "D6,7",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "12/10/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos2",
        title: "Examining the neurological system: cranial nerves",
        teachers: "Kalli Spencer",
        groups: "D1-5",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "13/10/2026",
        start: "9:00",
        end: "10:00",
        type: "L37",
        title: "Higher Cortical Function 2 - Sleep",
        teachers: "Felix Aplin",
        groups: "",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "13/10/2026",
        start: "10:00",
        end: "11:00",
        type: "L38",
        title: "Cerebellum",
        teachers: "Tom Duncan",
        groups: "",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "13/10/2026",
        start: "11:00",
        end: "12:00",
        type: "L39",
        title: "Advance Directives",
        teachers: "Frank Brennan, Louise Baird",
        groups: "",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "13/10/2026",
        start: "13:00",
        end: "15:00",
        type: "SG8",
        title: "Cranial Nerve Lesion",
        teachers: "Tom Duncan",
        groups: "D",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "13/10/2026",
        start: "15:00",
        end: "17:00",
        type: "SG8",
        title: "Cranial Nerve Lesion",
        teachers: "Tom Duncan",
        groups: "C",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "13/10/2026",
        start: "13:00",
        end: "15:00",
        type: "P11",
        title: "QMP Weighing the Evidence",
        teachers: "Amir Ariff",
        groups: "C",
        location: "WWG06-07"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "13/10/2026",
        start: "15:00",
        end: "17:00",
        type: "P11",
        title: "QMP Weighing the Evidence",
        teachers: "Amir Ariff",
        groups: "D",
        location: "WWG06-07"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "13/10/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos2",
        title: "Examining the neurological system: cranial nerves",
        teachers: "Kalli Spencer",
        groups: "B1-5",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "13/10/2026",
        start: "12:00",
        end: "14:00",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "B8,9",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "13/10/2026",
        start: "14:30",
        end: "16:30",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "B6,7",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "14/10/2026",
        start: "9:00",
        end: "10:00",
        type: "Plenary3",
        title: "Barbara Parkinsons",
        teachers: "Fred von Wegnner, James Colebatch",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "14/10/2026",
        start: "10:00",
        end: "11:00",
        type: "L40",
        title: "Treatments for Parkinson's Disease",
        teachers: "James Colebatch",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "14/10/2026",
        start: "13:00",
        end: "15:00",
        type: "SG9",
        title: "Treatment Strategies for Parkinson's disease",
        teachers: "Natasha Kumar",
        groups: "A",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "14/10/2026",
        start: "15:00",
        end: "17:00",
        type: "SG9",
        title: "Treatment Strategies for Parkinson's disease",
        teachers: "Natasha Kumar",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "14/10/2026",
        start: "11:00",
        end: "13:00",
        type: "P11",
        title: "QMP Weighing the Evidence",
        teachers: "Amir Ariff",
        groups: "A",
        location: "WWG06-07"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "14/10/2026",
        start: "13:00",
        end: "14:00",
        type: "T6",
        title: "Cranial Nerve Lesions",
        teachers: "Tom Duncan",
        groups: "B,D",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "14/10/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos2",
        title: "Examining the neurological system: cranial nerves",
        teachers: "Kalli Spencer",
        groups: "C1-5",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "14/10/2026",
        start: "12:00",
        end: "14:00",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "C8,9",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "14/10/2026",
        start: "14:30",
        end: "16:30",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "C6,7",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/10/2026",
        start: "9:00",
        end: "10:00",
        type: "L41",
        title: "Pharmacology of Alzheimers Disease",
        teachers: "Natasha Kumar",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/10/2026",
        start: "10:00",
        end: "11:00",
        type: "L42",
        title: "Ethics - Whose Decision?",
        teachers: "Linda Sheahan",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/10/2026",
        start: "11:00",
        end: "12:00",
        type: "L43",
        title: "Neurodegenerative Disease",
        teachers: "Scott Kim",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/10/2026",
        start: "13:00",
        end: "15:00",
        type: "SG9",
        title: "Treatment Strategies for Parkinson's disease",
        teachers: "Natasha Kumar",
        groups: "D",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/10/2026",
        start: "15:00",
        end: "17:00",
        type: "SG9",
        title: "Treatment Strategies for Parkinson's disease",
        teachers: "Natasha Kumar",
        groups: "C",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/10/2026",
        start: "13:00",
        end: "15:00",
        type: "P12",
        title: "Brainstem",
        teachers: "Tom Duncan",
        groups: "C1-8",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/10/2026",
        start: "15:00",
        end: "17:00",
        type: "P12",
        title: "Brainstem",
        teachers: "Tom Duncan",
        groups: "B1-8",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/10/2026",
        start: "12:00",
        end: "14:00",
        type: "P13",
        title: "Pharmacology for Neurodegenerative Disease: from biomarkers to treatment",
        teachers: "Natasha Kumar",
        groups: "B5-10,C9-10",
        location: "WW115"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/10/2026",
        start: "15:00",
        end: "17:00",
        type: "P13",
        title: "Pharmacology for Neurodegenerative Disease: from biomarkers to treatment",
        teachers: "Natasha Kumar",
        groups: "D3-10",
        location: "WW115"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/10/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos2",
        title: "Examining the neurological system: cranial nerves",
        teachers: "Kalli Spencer",
        groups: "A1-5",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/10/2026",
        start: "12:00",
        end: "14:00",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "A8,9",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "15/10/2026",
        start: "14:30",
        end: "16:30",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "A6,7",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "16/10/2026",
        start: "9:00",
        end: "11:00",
        type: "P12",
        title: "Brainstem",
        teachers: "Tom Duncan",
        groups: "D5,10,A5,10,C9,10,B9,10",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "16/10/2026",
        start: "11:00",
        end: "13:00",
        type: "P12",
        title: "Brainstem",
        teachers: "Tom Duncan",
        groups: "D1-4,D6-9",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "16/10/2026",
        start: "13:00",
        end: "15:00",
        type: "P12",
        title: "Brainstem",
        teachers: "Tom Duncan",
        groups: "A1-4,A6-9",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "16/10/2026",
        start: "9:00",
        end: "11:00",
        type: "P13",
        title: "Pharmacology for Neurodegenerative Disease: from biomarkers to treatment",
        teachers: "Natasha Kumar",
        groups: "C1-4,A8-9,D1,2",
        location: "WW115"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "16/10/2026",
        start: "12:00",
        end: "14:00",
        type: "P13",
        title: "Pharmacology for Neurodegenerative Disease: from biomarkers to treatment",
        teachers: "Natasha Kumar",
        groups: "C5-8,B1-4",
        location: "WW115"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "16/10/2026",
        start: "15:00",
        end: "17:00",
        type: "P13",
        title: "Pharmacology for Neurodegenerative Disease: from biomarkers to treatment",
        teachers: "Natasha Kumar",
        groups: "A1-7,10",
        location: "WW115"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "16/10/2026",
        start: "12:00",
        end: "14:00",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "A10,D10",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "16/10/2026",
        start: "14:30",
        end: "16:30",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "B10,C10",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "19/10/2026",
        start: "9:00",
        end: "10:00",
        type: "L44",
        title: "Introduction to dementia",
        teachers: "William Lawson",
        groups: "",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "19/10/2026",
        start: "10:00",
        end: "11:00",
        type: "L45",
        title: "Aboriginal Ageing and Dementia",
        teachers: "Louise Lavrencic, Alison Timbery",
        groups: "",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "19/10/2026",
        start: "11:00",
        end: "12:00",
        type: "T7",
        title: "Ethics 2 Whose Decision Is it?",
        teachers: "Sarah Baldwin",
        groups: "A",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "19/10/2026",
        start: "12:00",
        end: "13:00",
        type: "T7",
        title: "Ethics 2 Whose Decision Is it?",
        teachers: "Sarah Baldwin",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "19/10/2026",
        start: "13:00",
        end: "15:00",
        type: "SG10",
        title: "Poject and Assignment presentations",
        teachers: "Frederic Von Wegner",
        groups: "A",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "19/10/2026",
        start: "15:00",
        end: "17:00",
        type: "SG10",
        title: "Poject and Assignment presentations",
        teachers: "Frederic Von Wegner",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "19/10/2026",
        start: "12:00",
        end: "13:00",
        type: "T8",
        title: "Recovery and rehabilitation",
        teachers: "Greg Bowman",
        groups: "A",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "19/10/2026",
        start: "13:00",
        end: "14:00",
        type: "T8",
        title: "Recovery and rehabilitation",
        teachers: "Greg Bowman",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "19/10/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos3",
        title: "The neurological system: putting it all together",
        teachers: "Kalli Spencer",
        groups: "D6-10",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "19/10/2026",
        start: "12:00",
        end: "14:00",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "D3,4",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "19/10/2026",
        start: "14:30",
        end: "16:30",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "D1,2",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "20/10/2026",
        start: "9:00",
        end: "10:00",
        type: "L46",
        title: "Aged Care & Health Care Systems",
        teachers: "Peter Gonski",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "20/10/2026",
        start: "10:00",
        end: "11:00",
        type: "L47",
        title: "Brain Recovery",
        teachers: "Russell Chander",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "20/10/2026",
        start: "11:00",
        end: "12:00",
        type: "T7",
        title: "Ethics 2 Whose Decision Is it?",
        teachers: "Sarah Baldwin",
        groups: "D",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "20/10/2026",
        start: "12:00",
        end: "13:00",
        type: "T7",
        title: "Ethics 2 Whose Decision Is it?",
        teachers: "Sarah Baldwin",
        groups: "C",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "20/10/2026",
        start: "13:00",
        end: "15:00",
        type: "SG10",
        title: "Poject and Assignment presentations",
        teachers: "Frederic Von Wegner",
        groups: "D",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "20/10/2026",
        start: "15:00",
        end: "17:00",
        type: "SG10",
        title: "Poject and Assignment presentations",
        teachers: "Frederic Von Wegner",
        groups: "C",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "20/10/2026",
        start: "12:00",
        end: "13:00",
        type: "T8",
        title: "Recovery and rehabilitation",
        teachers: "Greg Bowman",
        groups: "D",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "20/10/2026",
        start: "13:00",
        end: "14:00",
        type: "T8",
        title: "Recovery and rehabilitation",
        teachers: "Greg Bowman",
        groups: "C",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "20/10/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos3",
        title: "The neurological system: putting it all together",
        teachers: "Kalli Spencer",
        groups: "B6-10",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "20/10/2026",
        start: "12:00",
        end: "14:00",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "B3,4",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "20/10/2026",
        start: "14:30",
        end: "16:30",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "B1,2",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/10/2026",
        start: "9:00",
        end: "10:00",
        type: "L48",
        title: "Psychiatry of Neurodegeneration",
        teachers: "Henry Brodaty",
        groups: "",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/10/2026",
        start: "10:00",
        end: "11:00",
        type: "L49",
        title: "Healthy Ageing: Psychosocial Aspects",
        teachers: "Carmelle Peisah",
        groups: "",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/10/2026",
        start: "11:00",
        end: "12:00",
        type: "T9",
        title: "Cerebellum",
        teachers: "Tom Duncan",
        groups: "",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/10/2026",
        start: "13:00",
        end: "15:00",
        type: "SG11",
        title: "Atypical PD and Palliative Care",
        teachers: "Fred von Wegner, Sarah Baldwin",
        groups: "A",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/10/2026",
        start: "15:00",
        end: "17:00",
        type: "SG11",
        title: "Atypical PD and Palliative Care",
        teachers: "Fred von Wegner, Sarah Baldwin",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/10/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos3",
        title: "The neurological system: putting it all together",
        teachers: "Kalli Spencer",
        groups: "C6-10",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/10/2026",
        start: "12:00",
        end: "14:00",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "C3,4",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "21/10/2026",
        start: "14:30",
        end: "16:30",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "C1,2",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/10/2026",
        start: "9:00",
        end: "10:00",
        type: "L50",
        title: "Exercise rehabilitation for neurodegenerative diseases",
        teachers: "Yoshiro Okubo",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/10/2026",
        start: "10:00",
        end: "11:00",
        type: "L51",
        title: "Traumatic Brain Injury",
        teachers: "Nicodemus Tedla",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/10/2026",
        start: "13:00",
        end: "15:00",
        type: "SG11",
        title: "Atypical PD and Palliative Care",
        teachers: "Fred von Wegner, Sarah Baldwin",
        groups: "D",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/10/2026",
        start: "15:00",
        end: "17:00",
        type: "SG11",
        title: "Atypical PD and Palliative Care",
        teachers: "Fred von Wegner, Sarah Baldwin",
        groups: "C",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/10/2026",
        start: "13:00",
        end: "15:00",
        type: "P14",
        title: "The basal ganglia and limbic system",
        teachers: "Tom Duncan",
        groups: "C1-8",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/10/2026",
        start: "15:00",
        end: "17:00",
        type: "P14",
        title: "The basal ganglia and limbic system",
        teachers: "Tom Duncan",
        groups: "B1-8",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/10/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos3",
        title: "The neurological system: putting it all together",
        teachers: "Kalli Spencer",
        groups: "A6-10",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/10/2026",
        start: "12:00",
        end: "14:00",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "A3,4",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "22/10/2026",
        start: "14:30",
        end: "16:30",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "A1,2",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "23/10/2026",
        start: "9:00",
        end: "11:00",
        type: "P14",
        title: "The basal ganglia and limbic system",
        teachers: "Tom Duncan",
        groups: "D5,10,A5,10,C9,10,B9,10",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "23/10/2026",
        start: "11:00",
        end: "13:00",
        type: "P14",
        title: "The basal ganglia and limbic system",
        teachers: "Tom Duncan",
        groups: "D1-4,D6-9",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "23/10/2026",
        start: "13:00",
        end: "15:00",
        type: "P14",
        title: "The basal ganglia and limbic system",
        teachers: "Tom Duncan",
        groups: "A1-4,A6-9",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "23/10/2026",
        start: "12:00",
        end: "14:00",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "A5,D5",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "23/10/2026",
        start: "14:30",
        end: "16:30",
        type: "CS3",
        title: "Neuro Simulated Patient SOCA and MOCK OSCE Practice Session",
        teachers: "Kalli Spencer",
        groups: "B5,C5",
        location: "WWG39"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "26/10/2026",
        start: "9:00",
        end: "10:00",
        type: "L52",
        title: "Sectional Neuroanatomy & Imaging",
        teachers: "Reza Shirazi",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "26/10/2026",
        start: "10:00",
        end: "11:00",
        type: "L53",
        title: "Caring for the patients with dementia",
        teachers: "Fiona Tran",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "26/10/2026",
        start: "11:00",
        end: "12:00",
        type: "T10",
        title: "Basal Ganglia",
        teachers: "Tom Duncan",
        groups: "",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "26/10/2026",
        start: "13:00",
        end: "15:00",
        type: "SG12",
        title: "Living with dementia",
        teachers: "Louise Baird, Katya Numbers, Sarah Baldwin",
        groups: "A",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "26/10/2026",
        start: "15:00",
        end: "17:00",
        type: "SG12",
        title: "Living with dementia",
        teachers: "Louise Baird, Katya Numbers, Sarah Baldwin",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "26/10/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos3",
        title: "The neurological system: putting it all together",
        teachers: "Kalli Spencer",
        groups: "D1-5",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "27/10/2026",
        start: "9:00",
        end: "10:00",
        type: "L54",
        title: "Physiology Review",
        teachers: "Catherine Guo",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "27/10/2026",
        start: "10:00",
        end: "11:00",
        type: "T11",
        title: "Integrating Concepts",
        teachers: "Tom Duncan, Frederick Von Wegner, Natasha Kumar",
        groups: "",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "27/10/2026",
        start: "13:00",
        end: "15:00",
        type: "SG12",
        title: "Living with dementia",
        teachers: "Louise Baird, Katya Numbers, Sarah Baldwin",
        groups: "D",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "27/10/2026",
        start: "15:00",
        end: "17:00",
        type: "SG12",
        title: "Living with dementia",
        teachers: "Louise Baird, Katya Numbers, Sarah Baldwin",
        groups: "C",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "27/10/2026",
        start: "11:00",
        end: "13:00",
        type: "P15",
        title: "Human Aspects of Living with neuro-degenerative diseases (Psychiatry)",
        teachers: "Katya Numbers",
        groups: "C",
        location: "WWG06"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "27/10/2026",
        start: "15:00",
        end: "17:00",
        type: "P15",
        title: "Human Aspects of Living with neuro-degenerative diseases (Psychiatry)",
        teachers: "Katya Numbers",
        groups: "D",
        location: "WWG06"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "27/10/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos3",
        title: "The neurological system: putting it all together",
        teachers: "Kalli Spencer",
        groups: "B1-5",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/10/2026",
        start: "9:00",
        end: "11:00",
        type: "L55",
        title: "Neuroanatomy Review",
        teachers: "Tom Duncan, Kosta Kotsidis",
        groups: "",
        location: "Oshane 104"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/10/2026",
        start: "13:00",
        end: "15:00",
        type: "SG13",
        title: "Review, Wrap up, Practice",
        teachers: "Natasha Kumar",
        groups: "A",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/10/2026",
        start: "15:00",
        end: "17:00",
        type: "SG13",
        title: "Review, Wrap up, Practice",
        teachers: "Natasha Kumar",
        groups: "B",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/10/2026",
        start: "11:00",
        end: "13:00",
        type: "P15",
        title: "Human Aspects of Living with neuro-degenerative diseases (Psychiatry)",
        teachers: "Katya Numbers",
        groups: "B",
        location: "WWG06"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/10/2026",
        start: "15:00",
        end: "17:00",
        type: "P15",
        title: "Human Aspects of Living with neuro-degenerative diseases (Psychiatry)",
        teachers: "Katya Numbers",
        groups: "A",
        location: "WWG06"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "28/10/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos3",
        title: "The neurological system: putting it all together",
        teachers: "Kalli Spencer",
        groups: "C1-5",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "29/10/2026",
        start: "9:00",
        end: "10:00",
        type: "L56",
        title: "Pharmacology Review",
        teachers: "Natasha Kumar",
        groups: "",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "29/10/2026",
        start: "10:00",
        end: "11:00",
        type: "L57",
        title: "Formative Feedback",
        teachers: "Frederick von Wegner, Tom Duncan, Natasha Kumar",
        groups: "",
        location: "online"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "29/10/2026",
        start: "13:00",
        end: "15:00",
        type: "SG13",
        title: "Review, Wrap up, Practice",
        teachers: "Natasha Kumar",
        groups: "D",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "29/10/2026",
        start: "15:00",
        end: "17:00",
        type: "SG13",
        title: "Review, Wrap up, Practice",
        teachers: "Natasha Kumar",
        groups: "C",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "29/10/2026",
        start: "13:00",
        end: "15:00",
        type: "P16",
        title: "Coronal Slices of the Forebrain",
        teachers: "Tom Duncan",
        groups: "C1-8",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "29/10/2026",
        start: "15:00",
        end: "17:00",
        type: "P16",
        title: "Coronal Slices of the Forebrain",
        teachers: "Tom Duncan",
        groups: "B1-8",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "29/10/2026",
        start: "13:00",
        end: "17:00",
        type: "Hos3",
        title: "The neurological system: putting it all together",
        teachers: "Kalli Spencer",
        groups: "A1-5",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "30/10/2026",
        start: "9:00",
        end: "11:00",
        type: "P16",
        title: "Coronal Slices of the Forebrain",
        teachers: "Tom Duncan",
        groups: "D5,10,A5,10,C9,10,B9,10",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "30/10/2026",
        start: "11:00",
        end: "13:00",
        type: "P16",
        title: "Coronal Slices of the Forebrain",
        teachers: "Tom Duncan",
        groups: "D1-4,D6-9",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "30/10/2026",
        start: "13:00",
        end: "15:00",
        type: "P16",
        title: "Coronal Slices of the Forebrain",
        teachers: "Tom Duncan",
        groups: "A1-4,A6-9",
        location: "BS 8A"
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "06/11/2026",
        start: "9:45",
        end: "12:00",
        type: "exam",
        title: "AEB End of Course Exam",
        teachers: "",
        groups: "",
        location: ""
    },
    {
        courseName: "MFAC1526: Ageing & Endings B",
        date: "10/11/2026",
        start: "9:00",
        end: "15:00",
        type: "exam",
        title: "Y1&2 Prac exams",
        teachers: "",
        groups: "",
        location: ""
    }
]